<predefined> ::= 'loopBreakConst = 200\ni0 = int()\nres0 = bool()\n'<code>
<code> ::= <code><statement>'\n'|<statement>'\n'
<statement> ::= <assign>|<for>|<if>
<assign> ::= <bool_var>' = '<bool_const>
<for > ::= 'loopBreak = 0\nfor i0 in range('<int>','<int_var>'):{:\n'<code>'\nif loopBreak > loopBreakConst:{:\nbreak\n:}loopBreak += 1\n:}'
<if > ::= 'if '<bool> ':{:\ n '<code>':}'
<comp_op> ::= '!='
<bool> ::= <int>' '<comp_op>' '<int>
<bool_const> ::= 'True'|'False'
<bool_var> ::= 'res0'
<int> ::= <int_var>|'0'|'2'|'mod('<int_var>', '<int_var>')'
<int_var> ::= 'i0'|'in0'